---
defaults:
  - plot: simple
  - benchmark_profiler: simple
  - log: mlflow

# another alternative if you don't have any callbacks is to remove it from the
# defaults list and just use
callbacks: []

plot:
  callbacks:
    # Add plot callbacks here.
    - _target_: anemoi.training.diagnostics.callbacks.plot.BatchOutputPlot
      tag_infix: ens
      dataset_names: ["data"]
      sample_idx: ${diagnostics.plot.sample_idx}
      parameters: ${diagnostics.plot.parameters}
      every_n_batches: ${diagnostics.plot.frequency.batch}
      members: null  # None for all members, list for specific members
      plot_fn:
        _target_: anemoi.training.diagnostics.evaluation.plotting.batch_output.ensemble_plot_fn
        _partial_: true
        accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm

    # Deterministic callbacks are also overloaded.
    - _target_: anemoi.training.diagnostics.callbacks.plot.LossCurvePlot
      dataset_names: ["data"] #TODO can make this a default in pydantic and remove here
      # group parameters by categories when visualizing contributions to the loss
      # one-parameter groups are possible to highlight individual parameters
      parameter_groups:
        moisture: [tp, cp, tcw]
        sfc_wind: [10u, 10v]
      every_n_batches: ${diagnostics.plot.frequency.batch}
    - _target_: anemoi.training.diagnostics.callbacks.plot.BatchOutputPlot
      tag_infix: spec
      dataset_names: ["data"]
      sample_idx: ${diagnostics.plot.sample_idx}
      parameters: ${diagnostics.plot.parameters}
      every_n_batches: ${diagnostics.plot.frequency.batch}
      plot_fn:
        _target_: anemoi.training.diagnostics.evaluation.plotting.batch_output.spectrum_plot_fn
        _partial_: true
    - _target_: anemoi.training.diagnostics.callbacks.plot.BatchOutputPlot
      tag_infix: histo
      dataset_names: ["data"]
      sample_idx: ${diagnostics.plot.sample_idx}
      parameters: ${diagnostics.plot.parameters}
      every_n_batches: ${diagnostics.plot.frequency.batch}
      plot_fn:
        _target_: anemoi.training.diagnostics.evaluation.plotting.batch_output.histogram_plot_fn
        _partial_: true
    - _target_: anemoi.training.diagnostics.callbacks.plot.GraphFeaturePlot
      dataset_names: ["data"] #TODO can make this a default in pydantic and remove here
      every_n_epochs: ${diagnostics.plot.frequency.epoch}

    # Overloaded BatchOutputPlot with sample_plot_fn returns per-member deterministic sample plots
    # - _target_: anemoi.training.diagnostics.callbacks.plot.BatchOutputPlot
    #   tag_infix: sample
    #   sample_idx: ${diagnostics.plot.sample_idx}
    #   parameters: ${diagnostics.plot.parameters}
    #   every_n_batches: ${diagnostics.plot.frequency.batch}
    #   plot_fn:
    #     _target_: anemoi.training.diagnostics.evaluation.plotting.batch_output.sample_plot_fn
    #     _partial_: true
    #     per_sample: 6
    #     accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm

debug:
  # this will detect and trace back NaNs / Infs etc. but will slow down training
  anomaly_detection: False


enable_checkpointing: True
checkpoint:
  every_n_minutes:
    save_frequency: 30 # Approximate, as this is checked at the end of every 50 training steps
    num_models_saved: 3 # If set to k, saves the 'last' k model weights in the training.

  every_n_epochs:
    save_frequency: 1
    num_models_saved: -1 # If set to -1, all checkpoints are kept ensuring runs can be continued/forked at any point in the training process

  every_n_train_steps:
    save_frequency: null # Does not scale with rollout
    num_models_saved: 0

enable_progress_bar: True
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 1

check_val_every_n_epoch: 1
print_memory_summary: False
