defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: encoder_decoder_only
- model: graphtransformer
- task: autoencoder
- training: single
- _self_

config_validation: True

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# system:
#   hardware:
#     num_gpus_per_node: 1

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDec
    latent_skip: False
  decoders:
    "0":
      target_node_features: [ "coordinates" ]
  processor:
    _target_: anemoi.models.layers.processor.NoOpProcessor

diagnostics:
  plot:
    callbacks:
      - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSample
        dataset_names: ${diagnostics.plot.datasets_to_plot}
        sample_idx: ${diagnostics.plot.sample_idx}
        per_sample : 6
        parameters:
        - z_500
        - t_850
        - u_850
        - v_850
        - 2t
        - tp
        every_n_batches: ${diagnostics.plot.frequency.batch}
        accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm
        precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
        colormaps: ${diagnostics.plot.colormaps}
