defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: hierarchical_2level_encoder_decoder_only
- model: graphtransformer
- task: autoencoder
- training: single
- _self_

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecHierarchical
    hidden_nodes_name: ["hidden_1", "hidden_2"]
  processor:
    _target_: anemoi.models.layers.processor.NoOpProcessor
  decoders:
    "0":
      target_node_features: [ "coordinates" ]


  upscale_mapper:
      # With omegaconf=2.4, the following will be supported ${model.decoders[0].mapper}
      _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
      num_channels: ${model.num_channels}
      trainable_size: ${model.edge_trainable_parameters.data2hidden}
      sub_graph_edge_attributes: ${model.attributes.edges}
      num_chunks: 4
      mlp_hidden_ratio: 4 # GraphTransformer/Transformer only; use 4 (mlp) or ~2.67 (glu/swiglu/geglu/reglu)
      mlp_implementation: mlp
      num_heads: 16 # GraphTransformer or Transformer only
      qk_norm: False
      cpu_offload: ${model.cpu_offload}
      gradient_checkpointing: True
      layer_kernels: ${model.layer_kernels}
      shard_strategy: "edges"
      graph_attention_backend: "triton"  # Options: "triton", "pyg"
      edge_pre_mlp: False
  downscale_mapper:
      _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
      num_channels: ${model.num_channels}
      trainable_size: ${model.edge_trainable_parameters.hidden2data}
      sub_graph_edge_attributes: ${model.attributes.edges}
      num_chunks: 4
      mlp_hidden_ratio: 4 # GraphTransformer/Transformer only; use 4 (mlp) or ~2.67 (glu/swiglu/geglu/reglu)
      mlp_implementation: mlp
      num_heads: 16 # GraphTransformer or Transformer only
      qk_norm: False
      cpu_offload: ${model.cpu_offload}
      gradient_checkpointing: True
      layer_kernels: ${model.layer_kernels}
      shard_strategy: "edges"
      graph_attention_backend: "triton"  # Options: "triton", "pyg"
      edge_pre_mlp: False

  enable_hierarchical_level_processing: False
  keep_batch_sharded: True

  node_trainable_parameters:
    hidden_1: 8
    hidden_2: 8

diagnostics:
  plot:
    callbacks:
      - _target_: anemoi.training.diagnostics.callbacks.plot.LossCurvePlot
        # group parameters by categories when visualizing contributions to the loss
        # one-parameter groups are possible to highlight individual parameters
        parameter_groups:
          moisture: [tp, cp, tcw]
          sfc_wind: [10u, 10v]
        every_n_batches: ${diagnostics.plot.frequency.batch}
      - _target_: anemoi.training.diagnostics.callbacks.plot.PlotReconstruction
        sample_idx: ${diagnostics.plot.sample_idx}
        per_sample : 6
        parameters: ${diagnostics.plot.parameters}
        every_n_batches: ${diagnostics.plot.frequency.batch}
        #Defining the accumulation levels for precipitation related fields and the colormap
        accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm
        precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
        colormaps: ${diagnostics.plot.colormaps}

# set to true to switch on config validation
config_validation: True
