defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer_multi_transport_tendency_edm
- task: forecaster
- training: edm_diffusion
- _self_


# set to true to switch on config validation
config_validation: True

training:
  transport:
    prediction_mode: tendency
