defaults:
- data: multi
- dataloader: multi
- diagnostics: evaluation_multi
- system: example
- graph: multi
- model: graphtransformer_multi_transport_edm
- task: forecaster
- training: edm_diffusion
- _self_


# set to true to switch on config validation
config_validation: True
