defaults:
- data: zarr
- dataloader: forecast_native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer
- task: temporal_downscaler
- training: single
- override training/training_loss: single_MSE_aggregation
- _self_

config_validation: True

data:
  frequency: null
  datasets:
    data:
      forcing:
        - "cos_latitude"
        - "cos_longitude"
        - "sin_latitude"
        - "sin_longitude"
        - "cos_julian_day"
        - "cos_local_time"
        - "sin_julian_day"
        - "sin_local_time"
        - "insolation"
        - "lsm"
        - "z"
      processors:
        normalizer:
          config:
            max: ["z"]
            none:
              - "cos_latitude"
              - "cos_longitude"
              - "sin_latitude"
              - "sin_longitude"
              - "cos_julian_day"
              - "cos_local_time"
              - "sin_julian_day"
              - "sin_local_time"
              - "insolation"

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# system:
#   hardware:
#     num_gpus_per_node: 1

diagnostics:
  plot:
    callbacks: []
  callbacks:
    - _target_: anemoi.training.diagnostics.callbacks.per_timestep_metrics.PerTimestepMetrics
      every_n_batches: 20

training:
  # Overwrites the tendency timestep used in the scaling to the output timestep so all lead times are normalised
  # by the same per-step statistics rather than their cumulative tendency statistics. Setting this timestep is
  # required when using a tendency scaler with task.output_left_boundary, since the 0h output step has no tendency statistics.
  # This does NOT activate the tendency scaler - to do this you must include the scaler in the loss configuration.
  scalers:
    datasets:
      data:
        stdev_tendency:
          timestep: ${task.output_timestep}
        var_tendency:
          timestep: ${task.output_timestep}
