num_channels: 1024
cpu_offload: False

keep_batch_sharded: True

model:
  _target_: anemoi.models.models.AnemoiModelEncProcDec
  hidden_nodes_name: "hidden"
  latent_skip: True

layer_kernels:
  # The layer_kernels can be adjusted per model component, but are defined here for convenience.
  LayerNorm:
    _target_: torch.nn.LayerNorm
  Linear:
    _target_: torch.nn.Linear
  Activation:
    _target_: torch.nn.GELU
  QueryNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False
  KeyNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False

processor:
  _target_: anemoi.models.layers.processor.GraphTransformerProcessor
  num_channels: ${model.num_channels}
  trainable_size: ${model.edge_trainable_parameters.hidden2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_layers: 16
  num_chunks: 4
  mlp_hidden_ratio: 4 # GraphTransformer/Transformer only; use 4 (mlp) or ~2.67 (glu/swiglu/geglu/reglu)
  mlp_implementation: mlp
  num_heads: 16 # GraphTransformer or Transformer only
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  gradient_checkpointing: True
  layer_kernels: ${model.layer_kernels}
  shard_strategy: "edges"
  graph_attention_backend: "triton"  # Options: "triton", "pyg"
  edge_pre_mlp: False

encoders:
  "0": # user-defined key. It will appear in the state-dict
    source_datasets: [ "data" ]
    dataset_fusing_strategy:  "not_supported" # Options: "not_supported" (only option now)
    mapper:
      _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
      num_channels: ${model.num_channels}
      trainable_size: ${model.edge_trainable_parameters.data2hidden}
      sub_graph_edge_attributes: ${model.attributes.edges}
      num_chunks: 4
      mlp_hidden_ratio: 4 # GraphTransformer/Transformer only; use 4 (mlp) or ~2.67 (glu/swiglu/geglu/reglu)
      mlp_implementation: mlp
      num_heads: 16 # GraphTransformer or Transformer only
      qk_norm: False
      cpu_offload: ${model.cpu_offload}
      gradient_checkpointing: True
      layer_kernels: ${model.layer_kernels}
      shard_strategy: "edges"
      graph_attention_backend: "triton"  # Options: "triton", "pyg"
      edge_pre_mlp: False


latent_aggregator:
  _target_: anemoi.models.layers.aggregator.SumAggregator

decoders:
  "0": # user-defined key. It will appear in the state-dict
    target_datasets: [ "data" ]
    target_node_features: [ "encoded_data" ] # options: coordinates, forcings, prognostics, trainable_parameters, encoded_data
    mapper:
      _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
      num_channels: ${model.num_channels}
      trainable_size: ${model.edge_trainable_parameters.hidden2data}
      sub_graph_edge_attributes: ${model.attributes.edges}
      num_chunks: 4
      mlp_hidden_ratio: 4 # GraphTransformer/Transformer only; use 4 (mlp) or ~2.67 (glu/swiglu/geglu/reglu)
      mlp_implementation: mlp
      num_heads: 16 # GraphTransformer or Transformer only
      initialise_data_extractor_zero: False
      qk_norm: False
      cpu_offload: ${model.cpu_offload}
      gradient_checkpointing: True
      layer_kernels: ${model.layer_kernels}
      shard_strategy: "edges"
      graph_attention_backend: "triton"  # Options: "triton", "pyg"
      edge_pre_mlp: False


residual:
  datasets:
    data:
      _target_: anemoi.models.layers.residual.SkipConnection # options: SkipConnection, TruncatedConnection
      step: -1 # use the latest step as skip connection

output_mask:
  datasets:
    data:
      _target_: anemoi.training.utils.masks.NoOutputMask

node_trainable_parameters:
  data: 8
  hidden: 8

edge_trainable_parameters:
  data2hidden: 8
  hidden2hidden: 8
  hidden2data: 8
# Torch compile configuration
# A list of modules present in the model, which will be compiled
# You can optionally pass options to torch.compile with the 'options' key
#
# Below is an explanation of some common parameters to torch.compile
# For a full list of possible parameters, consult the documenation for torch compile
#       https://docs.pytorch.org/docs/stable/generated/torch.compile.html
#
# dynamic (bool): When True, it will try to avoid recompilation by generating
#       as general a kernel as possible. But the performance of the general
#       kernel might be worse. When False, it will generate a specific
#       kernel for each input shape (until the configurable recompile
#       limit has been hit), leading to possibly better performance but
#       more recompilations
# mode (str): Different compilation modes, allowing you to trade off
#       compilation time versus potential performance. See the
#       torch.compile documentation for list of possible modes
# fullgraph (bool): When True, torch.compile will error when it hits a
#       section of code it can't compile. When False, it will fallback to
#       non-compiled ("eager") execution for those lines.
# options (dict): a dict of further options which can be passed to torch.compile
compile:
  - module: anemoi.models.layers.conv.GraphTransformerConv

attributes:
  edges:
    - edge_length
    - edge_dirs
  nodes: []

# Bounding configuration
bounding: #These are applied in order
  datasets:
    data:
      # Bound tp (total precipitation) with a Relu bounding layer
      # ensuring a range of [0, infinity) to avoid negative precipitation values.
      - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
        variables:
          - tp

      # [OPTIONAL] Bound cp (convective precipitation) as a fraction of tp.
      # This guarantees that cp is physically consistent with tp by restricting cp
      # to a fraction of tp [0 to 1]. Uncomment the lines below to apply.
      # NOTE: If this bounding strategy is used, the normalization of cp must be
      # changed to "std" normalization, and the "cp" statistics should be remapped
      # to those of tp to ensure consistency.

      # - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
      #   variables:
      #   - cp
      #   min_val: 0
      #   max_val: 1
      #   total_var: tp

      # [OPTIONAL] NormalizedReluBounding
      # This is an extension of the Relu bounding in case the thrshold to be used
      # is not 0. For example, in case of the sea surface temperature we don't use
      # [0, infinity), buth rather [-2C, infinity). We do not want the water
      # temperature to be below the freezing temperature.

      # - _target_: anemoi.models.layers.bounding.NormalizedReluBounding
      #   variables: [sst]
      #   min_val: [-2]
      #   normalizer: ['mean-std']
