# (C) Copyright 2024 Anemoi contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.
[build-system]
requires = [ "setuptools>=60", "setuptools-scm>=8" ]

[project]
name = "anemoi-graphs"
description = "A package to build graphs for data-driven forecasts."
keywords = [ "ai", "graphs", "tools" ]
license = { file = "LICENSE" }
authors = [
  { name = "European Centre for Medium-Range Weather Forecasts (ECMWF)", email = "software.support@ecmwf.int" },
]
requires-python = ">=3.11,<3.14"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = [ "version" ]
dependencies = [
  "anemoi-utils>=0.4.11",
  "hydra-core>=1.3",
  "matplotlib>=3.6",
  "networkx>=3.1",
  "numpy>=1.26",
  "plotly>=5.19",
  "scikit-learn>=1.5",
  "scipy>=1.6",
  "torch>=2.6,<2.11",
  "torch-geometric>=2.3.1",
  "typeguard>=4",
]
optional-dependencies.all = [ "anemoi-graphs[anemoi,healpix,hex,tri,xarray]" ]
optional-dependencies.anemoi = [ "anemoi-datasets>=0.5.21" ]
optional-dependencies.dev = [ "anemoi-graphs[docs,tests]" ]
optional-dependencies.docs = [
  "nbsphinx",
  "pandoc",
  "requests",
  "sphinx<8.2; python_version<'3.11'",   # Fixed until nbsphinx updates
  "sphinx>=8.2; python_version>='3.11'",
  "sphinx-argparse",
  "sphinx-rtd-theme",
  "termcolor",
  "tomli",
]
optional-dependencies.healpix = [ "healpy>=1.17" ]
optional-dependencies.hex = [ "h3>=4" ]
optional-dependencies.tests = [ "hypothesis>=6.11", "pytest>=8", "pytest-mock>=3" ]
optional-dependencies.tri = [ "trimesh>=4.1" ]
optional-dependencies.xarray = [
  "netcdf4>1.7,<1.7.3",
  "xarray<2026.9",      # this version removes zarr-python 2.x compatibility
  "zarr<3",
]
urls.Documentation = "https://anemoi-graphs.readthedocs.io/"
urls.Homepage = "https://github.com/ecmwf/anemoi-graphs/"
urls.Issues = "https://github.com/ecmwf/anemoi-graphs/issues"
urls.Repository = "https://github.com/ecmwf/anemoi-graphs/"
scripts.anemoi-graphs = "anemoi.graphs.__main__:main"

[tool.setuptools]
package-data."anemoi.graphs" = [ "py.typed" ]

[tool.setuptools_scm]
version_file = "src/anemoi/graphs/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"
root = ".."
tag_regex = "^graphs-(?P<version>[vV]?[0-9]+[^-]*)"
fallback_version = "0.0.0"
git_describe_command = "git describe --dirty --tags --long --match 'graphs-*[0-9]*'"

[tool.ruff]
lint.extend-select = [ "TID251" ]  # banned API usage
lint.flake8-tidy-imports.banned-api."anemoi.training".msg = "Do not import from anemoi-training in anemoi-graphs."
